site_name: MeshCore
site_url: https://meshcore-brasil.github.io
theme:
  favicon: favicon.png
  name: landing
  custom_dir: overrides
  avatar: assets/repeater.png
  toc_level: 2
  share_btn: false
  tagline: |
    Brasil
  header_layout: 
    - avatar
    - title
    - tagline
  # colors
  primary_color: "#d9a35d"
  secondary_color: "#4862a6"
  tertiary_color: "#b75034"
  base_color: "#ffffff"
  mantle_color: "#f2f2f2"
  crust_color: "#d2d2d2"
  overlay_color: "#b2b2b2"
  text_color: "#161616"
  hltext_color: "#f2f2f2"
  # colors (dark)
  primary_color_dark: "#d9a35d"
  secondary_color_dark: "#46B1C9"
  tertiary_color_dark: "#D4ADCF"
  base_color_dark: "#212530"
  mantle_color_dark: "#111318"
  crust_color_dark: "#050608"
  overlay_color_dark: "#000000"
  text_color_dark: "#f2f2f2"
  hltext_color_dark: "#161616"

markdown_extensions:
  - admonition

nav:
  - Brasil: index.md
  - Gerador de Nomes para Repetidoras: nomes-repetidoras.md

extra_css:
  - styles/extra.css

extra_javascript:
  - js/repeater-name-generator.js

plugins:
  - git-revision-date-localized:
      enable_creation_date: false
      type: date
  - git-committers:
      repository: MeshCore-Brasil/meshcore-brasil.github.io
      branch: main
